### ISSUE TITLE
Profile pages

### ISSUE THREAD

**Issue by slinlee** [slavingia/fweb3.xyz#71]
It could include:
- their 9 dots/progress - easy, done already
- their NFT - the quick and dirty version is to link to https://opensea.io/[account]?search[query]=fweb3
- who they received FWEB3 from - easy https://docs.polygonscan.com/api-endpoints/accounts#get-a-list-of-erc-20-token-transfer-events-by-address (filtered by "to === address")
- whom they sent FWEB3 to. - easy https://docs.polygonscan.com/api-endpoints/accounts#get-a-list-of-erc-20-token-transfer-events-by-address (filtered by "from === address")
- FWEB3 balance - easy, done already

**Comment by slavingia** [comment]
ENS support would be great too, so i can send people to fweb3.xyz/s4h1l and it should just work 🚀

**Comment by slinlee** [comment]
> Could you do research into what is currently possible to fetch easily? If we know the data we could display, it will be quick to design and ship.

@slavingia I added some notes and it looks like most of it is available pretty easily via polygonscan. If you had any other thoughts about what should be on the profile page, let me know!

**Comment by thecryptodiver** [comment]
Had an idea for the profile page based on the above information -
![profile-page](https://user-images.githubusercontent.com/85821373/155392001-7c39555e-fa76-44e3-8d22-757b07d48a81.png)

**Comment by slavingia** [comment]
really cool take!

**Comment by slinlee** [comment]
@thecryptodiver 
> And if the logged-in user is the same as the profile one, we could also show instructions related to the task.

Interesting. If this is the profile page, are there different things you'd want to put on the default homepage?

**Comment by tksumanth1994** [comment]
> Interesting. If this is the profile page, are there different things you'd want to put on the default homepage?

Yeah! Even though both pages might have same info right now, I think over time these will evolve differently, once more tasks & challenges come into picture.

Also might also redirect the user to the home page for instructions rather than showing it here. That will make sure there's a one stop for all the instructions.

@slinlee

**Comment by thecryptodiver** [comment]
> Interesting. If this is the profile page, are there different things you'd want to put on the default homepage?

Yeah! Even though both pages might have the same info right now, I think over time these will evolve differently, once more tasks & challenges come into the picture.

Also might also redirect the user to the home page for instructions rather than showing it here. That will make sure there's a one-stop for all the instructions.

@slinlee

**Comment by slinlee** [comment]
I was thinking the 'Transfer from' and 'transfers to' would be a neat network visualization. Or fweeb-family tree

**Comment by thecryptodiver** [comment]
@slavingia is there a particular reason you closed this? I was working on the frontend for this

**Comment by slavingia** [comment]
i just close stale tasks often (didn't see this being discussed in discord so didn't know if this was being worked on). feel free to open that PR, happy to take a look when ready!
